version: "3"

services:
  # ── HADOOP NAMENODE ──────────────────────────────────────
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"   # Hadoop Web UI
      - "9000:9000"   # HDFS port
    environment:
      - CLUSTER_NAME=bigdata
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  # ── HADOOP DATANODE ──────────────────────────────────────
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  # ── SPARK MASTER ─────────────────────────────────────────
  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"   # Spark Web UI
      - "7077:7077"   # Spark port
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./app:/app   # mount thư mục code vào container

  # ── SPARK WORKER ─────────────────────────────────────────
  spark-worker:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./app:/app

volumes:
  hadoop_namenode:
  hadoop_datanode: